# Generated by Django 3.1.2 on 2020-10-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('specDoctor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('isBusy', models.BooleanField()),
                ('docID', models.IntegerField()),
                ('patID', models.IntegerField()),
            ],
        ),
    ]
