# Generated by Django 3.1.2 on 2020-10-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('isBusy', models.BooleanField()),
                ('docID', models.IntegerField()),
                ('patID', models.IntegerField()),
            ],
        ),
    ]
